Revert "Reapply "Suppress WIN32OLE deprecation warnings for the time being""
This reverts commit f196750ccc57954a565785fe9cabd9c68ed8d754.

These changes lead to failure a Windows job on ruby/spec's CI.
The leaks detector reports that global variables are changed:

```
LeakError: Globals changed: {:verbose=>false, :debug=>false} to {:verbose=>nil, :debug=>false}
```