Guard spec not working on Windows
1)
IO#write on a file writes binary data if no encoding is given and multiple arguments passed ERROR
ArgumentError: ASCII incompatible string written for text mode IO without encoding conversion: UTF-32LE
D:/a/spec/spec/core/io/write_spec.rb:130:in `write'
D:/a/spec/spec/core/io/write_spec.rb:130:in `block (3 levels) in <top (required)>'
D:/a/spec/spec/core/io/write_spec.rb:129:in `open'
D:/a/spec/spec/core/io/write_spec.rb:129:in `block (2 levels) in <top (required)>'
D:/a/spec/spec/core/io/write_spec.rb:7:in `<top (required)>'