Quarantine a test case for Thread::Backtrace::Location#source_range
```
2040 ......................................................We are killing the stack canary set by intern, at <RubyVM::InstructionSequence:<top (required)>@/tmp/rubytest.zcb4v9/spec/3256-backtrace_location_source_range.rb:0>@pc=31
  watch out the C stack trace.
  == disasm: #<ISeq:<top (required)>@/tmp/rubytest.zcb4v9/spec/3256-backtrace_location_source_range.rb:1 (1,6)-(5,18)>
  local table (size: 1, argc: 0 [opts: 0, rest: -1, post: 0, block: -1, kw: -1@-1, kwrest: -1])
  [ 1] value@0
  0000 putnil                                                           (   1)[Li]
  0001 opt_getconstant_path                   <ic:0 Object>
  0003 opt_new                                <calldata!mid:new, argc:0, ARGS_SIMPLE>, 10
  0006 opt_send_without_block                 <calldata!mid:initialize, argc:0, FCALL|ARGS_SIMPLE>
  0008 jump                                   13
  0010 opt_send_without_block                 <calldata!mid:new, argc:0, ARGS_SIMPLE>
  0012 swap
  0013 pop
  0014 setlocal_WC_0                          value@0
  0016 getlocal_WC_0                          value@0                   (   2)[Li]
  0018 definesmethod                          :to_s, to_s
  0021 putobject                              ""                        (   5)[Li]
  0023 getlocal_WC_0                          value@0
  0025 dup
  0026 objtostring                            <calldata!mid:to_s, argc:0, FCALL|ARGS_SIMPLE>
  0028 anytostring
  0029 concatstrings                          2
  0031 intern
  0032 newarray                               1
  0034 leave

  == disasm: #<ISeq:to_s@/tmp/rubytest.zcb4v9/spec/3256-backtrace_location_source_range.rb:2 (2,6)-(4,9)>
  0000 dupchilledstring                       "\xFF"                    (   3)[LiCa]
  0002 opt_send_without_block                 <calldata!mid:+@, argc:0, ARGS_SIMPLE>
  0004 opt_getconstant_path                   <ic:0 Encoding::UTF_8>
  0006 opt_send_without_block                 <calldata!mid:force_encoding, argc:1, ARGS_SIMPLE>
  0008 leave                                                            (   4)[Re]
  make: *** [uncommon.mk:996: yes-test-spec] Aborted (core dumped)
  Error: Process completed with exit code 2.
```