Fix leaking globals ($VERBOSE and $DEBUG) in Windows' specs
This reverts commit 3caf9ce6bdf993a4b46540d8625938321881c197
"Suppress WIN32OLE deprecation warnings for the time being"
that leads to the following error:

```
An exception occurred during: WIN32OLE#_getproperty gets value
D:/a/spec/spec/library/win32ole/win32ole/_getproperty_spec.rb:12
WIN32OLE#_getproperty gets value ERROR
LeakError: Globals changed: {:verbose=>false, :debug=>false} to {:verbose=>nil, :debug=>false}
D:/a/spec/spec/library/win32ole/win32ole/_getproperty_spec.rb:7:in `block in <top (required)>'
D:/a/spec/spec/library/win32ole/win32ole/_getproperty_spec.rb:2:in `<top (required)>'
```