Made mock object name test specific
A mock object named X was producing the following error because it had
been used previously for something other than a class.

Float#=== calls 'other == self' if coercion fails ERROR
TypeError: X is not a class

Mock objecst should be very specifically named to prevent cross
specification side effects.