Quarantine a new test that causes a process termination on CRuby's CI
A tests process is terminated in the following way:

```
$ /home/runner/work/ruby/ruby/build/miniruby -I/home/runner/work/ruby/ruby/src/lib /home/runner/work/ruby/ruby/src/tool/runruby.rb --archdir=/home/runner/work/ruby/ruby/build --extout=.ext -- --yjit-call-threshold=1 --yjit-verify-ctx --yjit-code-gc /home/runner/work/ruby/ruby/src/spec/mspec/bin/mspec-run -B ../src/spec/default.mspec --debug
  ruby 4.1.0dev (2026-09-08T20:08:29Z pull/18681/merge 8451190201) +YJIT dev +PRISM [x86_64-linux]
       0 ............................................................
      60 ............................................We are killing the stack canary set by intern, at <RubyVM::InstructionSequence:block (3 levels) in <top (required)>@/home/runner/work/ruby/ruby/src/spec/ruby/language/symbol_spec.rb:100>@pc=16
  watch out the C stack trace.
  == disasm: #<ISeq:block (3 levels) in <top (required)>@/home/runner/work/ruby/ruby/src/spec/ruby/language/symbol_spec.rb:100 (100,4)-(102,5)>
  0000 putobject                              ""                        ( 101)[LiBc]
  0002 dupchilledstring                       "\xFF"
  0004 opt_send_without_block                 <calldata!mid:+@, argc:0, ARGS_SIMPLE>
  0006 opt_getconstant_path                   <ic:0 Encoding::UTF_8>
  0008 opt_send_without_block                 <calldata!mid:force_encoding, argc:1, ARGS_SIMPLE>
  0010 dup
  0011 objtostring                            <calldata!mid:to_s, argc:0, FCALL|ARGS_SIMPLE>
  0013 anytostring
  0014 concatstrings                          2
  0016 intern
  0017 leave                                                            ( 102)[Br]
  make: *** [uncommon.mk:996: yes-test-spec] Aborted (core dumped)
  Error: Process completed with exit code 2.
```